# Generated by Django 5.1 on 2024-08-30 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text2', models.TextField(blank=True, null=True, verbose_name='Текст2')),
                ('text3', models.TextField(blank=True, null=True, verbose_name='Текст3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение3')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(related_name='posts', to='post.tag', verbose_name='Теги')),
            ],
        ),
    ]
